codecov:
  strict_yaml_branch: "master"
  require_ci_to_pass: yes
  wait_for_ci: yes
  ignore:
    - "build/"
  disable_default_path_fixes: yes
fixes:
  - "::src/"
  - "::include/"

coverage:
  precision: 1
  round: down
  range: "70..100"

comment:
  layout: "diff,flags,tree"