name: Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
        architecture: "x64"
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: build docs
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        doxyfile-path: 'doxygen'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/doxygen