name: FDP C++ API

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y lcov libjsoncpp-dev curl libcurl4-openssl-dev libyaml-cpp-dev libhdf5-dev
      - name: Compile Library
        run: |
          cmake . -Bbuild -DFDPAPI_BUILD_TESTS=ON
          cmake --build build
      - name: Run Unit Tests
        run: |
          bash test/test_setup.sh
          cmake --build build --target test
          if [ $? -eq 0 ]; then
            echo "Unit tests completed successfully"
            exit 0
          else
            echo "Unit tests failed"
            exit 1
          fi
