name: SCRC C++ API

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y lcov libjsoncpp-dev curl libcurl4-openssl-dev libyaml-cpp-dev libhdf5-dev
      - name: Compile Library
        run: |
          cmake . -Bbuild -DSCRCAPI_BUILD_TESTS=ON -DSCRCAPI_CODE_COVERAGE=ON
          cmake --build build
      - name: Run Unit Tests
        run: |
          wget https://data.scrc.uk/data_product/SCRC:geography/scotland/lookup_table@0.1.0 -O test/test_table.h5
          wget https://data.scrc.uk/data_product/LSHTM:distributions/R0@0.1.0 -O test/test_dis.toml
          wget https://data.scrc.uk/data_product/EERA:fixed-parameters/T_rec@0.1.0 -O test/test_pe.toml
          wget https://data.scrc.uk/data_product/LSHTM:contact_matrices/national@0.20200811.0 -O test/test_array.h5
          cmake --build build --target test
          if [ $? -eq 0 ]; then
            echo "Unit tests completed successfully"
            exit 0
          else
            echo "Unit tests failed"
            exit 1
          fi
      - name: Code Coverage
        run: |
          cmake --build build --target coverage
          bash <(curl -s https://codecov.io/bash) -f build/scrcapi.info -K codecov.yml || echo "Codecov did not collect coverage reports"