name: SCRC C++ API

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y lcov libjsoncpp-dev curl libcurl4-openssl-dev libyaml-cpp-dev
      - name: Compile Library
        run: |
          cmake . -Bbuild -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
      - name: Run Unit Tests
        run: |
          cmake --build build --target test
          if [ $? -eq 0 ]; then
            echo "Unit tests completed successfully"
            exit 0
          else
            echo "Unit tests failed"
            exit 1
          fi
      - name: Code Coverage
        run: |
          cmake --build build --target coverage
          bash <(curl -s https://codecov.io/bash) -f build/scrcapi.info -K codecov.yml || echo "Codecov did not collect coverage reports"